apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: retail-store-ui-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: retail-store
  source:
    repoURL: https://github.com/saurabhpanth26/retail-store-app.git
    targetRevision: dev
    path: src/ui/chart
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: retail-store-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
