# Prod environment overrides
# TLS is terminated by ACM on the NLB — no cert-manager needed here.
replicaCount: 2

image:
  repository: 879385477302.dkr.ecr.ap-south-1.amazonaws.com/retail-store-ui
  tag: "prod-1705de6"

certManager:
  createClusterIssuer: false

app:
  endpoints:
    catalog: http://retail-store-catalog-prod:80
    carts: http://retail-store-cart-prod-carts:80
    orders: http://retail-store-orders-prod:80
    checkout: http://retail-store-checkout-prod:80

ingresses:
  - name: domain
    className: "nginx"
    hosts:
      - saurabh-devops.in
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
      nginx.ingress.kubernetes.io/proxy-body-size: "8m"
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    tls: []
