image:
  repository: 879385477302.dkr.ecr.ap-south-1.amazonaws.com/retail-store-ui
  tag: "dev-4455a3a"

app:
  endpoints:
    catalog: http://retail-store-catalog-dev:80
    carts: http://retail-store-cart-dev-carts:80
    checkout: http://retail-store-checkout-dev:80
    orders: http://retail-store-orders-dev:80

app:
  endpoints:
    catalog: http://retail-store-catalog-dev:80
    carts: http://retail-store-cart-dev-carts:80
    checkout: http://retail-store-checkout-dev:80
    orders: http://retail-store-orders-dev:80

# Dev environment overrides
# TLS is terminated by ACM on the NLB — no cert-manager needed here.
replicaCount: 1

certManager:
  createClusterIssuer: false

ingresses:
  - name: direct
    className: "nginx"
    hosts: []
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
      nginx.ingress.kubernetes.io/proxy-body-size: "8m"
  - name: domain
    className: "nginx"
    hosts:
      - dev.saurabh-devops.in
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
      nginx.ingress.kubernetes.io/proxy-body-size: "8m"
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    tls: []
