# Prod environment overrides
# TLS is terminated by ACM on the NLB — no cert-manager needed here.
replicaCount: 2

image:
  repository: 879385477302.dkr.ecr.ap-south-1.amazonaws.com/retail-store-ui
  tag: "prod-fab383f"

certManager:
  createClusterIssuer: false

ingresses:
  - name: domain
    className: "nginx"
    hosts:
      - saurabh-devops.in
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
      nginx.ingress.kubernetes.io/proxy-body-size: "8m"
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    tls: []
