apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarqube
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: retail-store

  sources:
    # Official SonarQube Helm chart
    - repoURL: https://SonarSource.github.io/helm-chart-sonarqube
      chart: sonarqube
      targetRevision: "10.8.0"
      helm:
        valueFiles:
          - $values/argocd/sonarqube/values.yaml

    # Values file from our git repo
    - repoURL: https://github.com/LondheShubham153/retail-store-sample-app
      targetRevision: gitops
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: sonarqube

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
